config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#top'
  get 'about', to: 'users#about'
  resources :books, only: [:create, :update, :destroy, :index, :show, :edit] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :update, :index, :edit] do
    resource :follows, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true

  has_many :comments
  has_many :favorites

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:name]

  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :comments
  has_many :follows
  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def followed_by?(user)
    follows.where(follow_id: user.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, :except => [:top, :about, :sign_up]



 protected
  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]

  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @user = User.find(@books.user_id)
    @comment = Comment.new
    @comments = @books.comments
  end

  def create
    book = Book.new
    book_get_params(book)
    book.user_id = current_user.id
    if book.save
      redirect_to book_path(book), notice: "Book was successfully created."
    else 
      flash[:notice] = "Error in create the book"
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Book was successfully updated."
    else
      flash[:notice] = "Error in update the book"
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed."
  end

  private

    def book_get_params(book)
      book.title = params[:book][:title]
      book.body = params[:book][:title]
    end

    def book_params
      params.require(:book).permit(:book, :title)
    end

    def correct_user
      book = Book.find(params[:id])
      if current_user != book.user
        redirect_to user_path(current_user)
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = current_user.comments.new(comment_params)
    book = Book.find(params[:book_id])
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    comment = Comment.find(params[:id])
    book = comment.book

    if comment.user != current_user
      redirect_to book_path(bood)
    end

    comment.destroy
    redirect_to book_path(book)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.new
    book = Book.find(params[:book_id])
    favorite.book_id = book.id
    favorite.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    follow = current_user.follows.new
    user = User.find(params[:user_id])
    follow.follow_id = user.id
    follow.save
    redirect_to user_path(user)
  end

  def destroy
    user = User.find(params[:user_id])
    follow = current_user.follows.find_by(follow_id: user.id)
    follow.destroy
    redirect_to user_path(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]

  def top
  end

  def about
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
    @followers = Follow.where(follow_id: @user.id).page(params[:page]).reverse_order
    @follows = @user.follows.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "User was successfully updated."
    else
      flash[:notice] = "Error in update the user"
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
    end

    def correct_user
      user = User.find(params[:id])
      if current_user != user
        redirect_to user_path(current_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<section class="col-lg-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
  <table class="table" style="margin-top: 130px">
    <tr>
      <th>name</th>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= user.introduction %></td>
    </tr>
  <% if current_user == user %>
      <tr>
        <th>follow</th>
        <td>follows:<%= user.follows.count %> followers:<%= Follow.where(follow_id: user.id).count %></td>
      </tr>
    </table>
    <%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  <% else %>
    <tr>
      <th>follow</th>
      <% if current_user.followed_by?(user) %> <!-- follow処理 -->
        <td>
          <%= link_to user_follows_path(user), method: :delete  do %>
          <i class="fa fa-heart" aria-hidden="ture" style="color: red;"></i>
          <% end %> follows:<%= user.follows.count %> followers:<%= Follow.where(follow_id: user.id).count %>
        </td>
      <% else %>
        <td>
          <%= link_to user_follows_path(user), method: :post  do %>
          <i class="far fa-heart" aria-hidden="ture" style="color: red;"></i>
          <% end %>  follows:<%= user.follows.count %> followers:<%= Follow.where(follow_id: user.id).count %>
        </td>
      <% end %>
      </tr>
    </table>
  <% end %>

  <h2 style="margin-top: 80px">New book</h2>
  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
        <%= @book.errors.count %>件のエラーが発生しました
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
    <p style="padding-top: 10px;">Title</p>
    <%= f.text_field :title, class: "col-xs-12 book_title" %>
    <p style="padding-top: 40px;">Opinion</p>
    <%= f.text_field :body, class: "col-xs-12 book_body" %>
    <div style="padding-top: 40px;">
      <%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
    </div>
  <% end %>

</section>

app/views/books/edit.html.erb
<section class="col-lg-6 col-lg-offset-3">
<%= h(flash[:notice]) %>
<h1>Editing Book</h1>

< %= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <p style="margin-top: 10px;">Title</p>
  <%= f.text_field :title, class: "col-lg-12 book_title" %>

  <p style="margin-top: 50px;">Opinion</p>
  <%= f.text_area :body, class: "col-lg-12 book_body" %><br>

  <div style="margin-top: 50px;">
    <%= f.submit "Update Book", class: "col-lg-12 btn btn-primary" %>
  </div>

<% end %>



<p style="margin-top: 100px"><%= link_to "Show", book_path(@book), class: "book_#{params[:id]}" %>|<%= link_to "Back", books_path, class: "books back" %></p>

</section>

app/views/books/index.html.erb
<%= h(flash[:notice]) %>
<div class="container">
  <div class="row">

    <%= render 'books/form', user: current_user %>

    <section class="col-lg-9">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %></td>
              <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          <%= paginate @books, class: "paginate" %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/books/show.html.erb
<%= h(flash[:notice]) %>
<div class="container">
  <div class="row">

    <%= render 'books/form', user: current_user %>

    <section class="col-lg-9">
      <h2>Book deteil</h2>
      <table class="table" style="font-size: 13px;">
        <tbody>
            <tr>
              <td style="height: 80px;"><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %><br><br><br>
                <%= link_to @user.name, user_path(@user), class: "user_#{@user.id}" %>
              </td>
              <td><%= link_to @books.title, book_path(@books), class: "book_#{@books.id}" %></td>
              <td><%= @books.body %></td>
              <td>
                <% if @books.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@books), method: :delete  do %>
                    <i class="fa fa-heart" aria-hidden="ture" style="color: red;"></i>
                    <%= @books.favorites.count %>いいね
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@books), method: :post  do %>
                      <i class="far fa-heart" aria-hidden="true" style="color: red;"></i>
                      <%= @books.favorites.count %>いいね
                    <% end %>
                <% end %>
              </td>
              <% if current_user == @user %>
                <td><%= link_to "Edit", edit_book_path(@books), class: "btn-sm btn-success edit_book_#{@books.id}" %></td>
                <td><%= link_to "Destroy", book_path(@books), method: :delete, class: "btn-sm btn-danger destroy_book_#{@books.id}" %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
      <div class="comment_box">
        <table class="table">
          <thead>
            <tr>
              <th>user</th>
              <th>comment</th>
            </tr>
          </thead>
          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <th><%= comment.user.name %></th>
                <th><%= comment.text %></th>
                <% if current_user == comment.user %>
                  <th><%= link_to "Destroy", book_comment_path(comment), method: :delete %></th>
                <% end %>
              </tr>
            <% end %>
          </tbody>

        </table>

        <%= form_for [@books,@comment] do |f| %>
          <%= f.label :text %>
          <%= f.text_area :text %>
          <%= f.submit "comment"%>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>

    <header style="background-color: black; color: white;">
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
            <span style="font-size: 20px">Bookers</span>
          </div>
          <div>
            <ul class="nav navbar-nav navbar-right text-muted" style="font-size: 13px;">
              <% if user_signed_in? %>
                <li class="">
                  <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
                </li>
                <li class="">
                  <%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %>
                </li>
                <li class="">
                  <%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %>
                </li>
                <li class="">
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
                </li>
              <% else %>
                <li class="text-light">
                  <%= link_to " Home", root_path, class: "glyphicon glyphicon-home text-light home" %>
                </li>
                <li class="">
                  <%= link_to " About", about_path, class: "glyphicon glyphicon-link about" %>
                </li>
                <li class="">
                  <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
                </li>
                <li class="">
                  <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  
    <%= yield %>

   <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-lg-3 col-lg-offset-9'>
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
    
  </body>
</html>

app/views/users/about.html.erb
<h1 class="col-lg-offset-1">Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true" style="font-weight: bold;">Bookers</span>!</h1>

<h1 class='jquery'>Hello jQuery!</h1>

<div id='container'>
  <div id='theTarget'>
    <div class='image1'></div>
    <div class='image2'></div>
    <div class='image3'></div>
    <div class='image4'></div>
    <div class='image5'></div>
  </div>
</div>

app/views/users/edit.html.erb
<%= h(flash[:notice]) %>
<section class="col-lg-6 col-lg-offset-3">
<h1>User info</h1>
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <%= @user.errors.count %>件のエラーが発生しました
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <p>Name</p>
  <%= f.text_field :name, class: "col-lg-12 name" %>

  <p style="margin-top: 50px;">Image</p>
  <%= f.attachment_field :profile_image, class: "user_image" %>

  <p style="margin-top: 15px;">Introduction</p>
  <%= f.text_area :introduction, class: "col-lg-12 introduction" %>

  <div style="margin-top: 80px;">
    <%= f.submit "Update User", class: "btn btn-primary col-lg-12" %>
  </div>

<% end %>
</section>

app/views/users/index.html.erb
<%= h(flash[:notice]) %>
<div class="container">
  <div class="row">

    <%= render 'books/form', user: @user %>

    <section class="col-lg-9">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show",  user_path(user), class: "user_#{user.id}" %></td>
            </tr>
          <% end %>
          <%= paginate @users, class: "paginate" %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/users/show.html.erb
<%= h(flash[:notice]) %>
<div class="container">
  <div class="row">

    <%= render 'books/form', user: @user %>

    <section class="col-lg-9">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %></td>
              <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          <%= paginate @books, class: "paginate" %>
        </tbody>
      </table>

      <h2>followers</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @followers.each do |follower| %>
            <tr>
              <td><%= attachment_image_tag follower.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %></td>
              <td><%= link_to follower.user.name, user_path(follower.user) %></td>
            </tr>
          <% end %>
          <%= paginate @followers, class: "paginate" %>
        </tbody>
      </table>

      <h2>follows</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>name</th>
          </tr>
        </thead>

        <tbody>
          <% @follows.each do |follow| %>
            <% user = User.find(follow.follow_id) %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", :size =>'40x40' %></td>
              <td><%= link_to user.name, user_path(user) %></td>
            </tr>
          <% end %>
          <%= paginate @follows, class: "paginate" %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/users/top.html.erb
<div class="col-lg-6 col-lg-offset-3">
<section style ="padding-left: 25px;">
  <div class="col-lg-offset-1">
    <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true" style="font-weight: bold;">Bookers</span>　!!</h1>
    <p>In <span class="glyphicon glyphicon-book" aria-hidden="true" style="font-weight: bold;">Bookers</span>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about varioius books!</p>
  </div>
  <div style="margin-bottom: 60px;">
    <%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
  </div>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
</section>
</div>